select ?metricid ?timestamp ?value ?methodExecution
	where {
		{
			?metricid rdf:type $metric$ .
			?metricid :hasTimeStamp ?timestamp .
			?metricid :hasDataValue ?value .
			?methodExecution :hasMeasurement ?metricid .
			?methodExecution :isMethodExecutionOf $method$ .
		}
	}
order by ?timestamp
