select ?metricid ?timestamp ?value
	where {
		{
			?metricid rdf:type $metric$ .
			?metricid :hasTimeStamp ?timestamp .
			?metricid :hasDataValue ?value .
			$application$ :hasMeasurement ?metricid.
			$system$ :hasMeasurement ?metricid.
		}
	}
order by ?timestamp
