PREFIX :<http://www.larkc.eu/ontologies/IMOntology.rdf#>

select ?metricid ?timestamp ?value
	where {
		{
			?metricid rdf:type $metric$ .
			?metricid :hasTimeStamp ?timestamp .
			?metricid :hasDataValue ?value .
		}
	}
order by ?timestamp
